# Generated by Django 3.2.10 on 2022-01-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0007_alter_user_random_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=150, unique=True, verbose_name='nickname'),
        ),
    ]
