# Generated by Django 3.2.10 on 2022-01-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='random_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
