# Generated by Django 3.2.11 on 2022-10-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220804_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_name',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(choices=[('20대', 'Twenty'), ('30대', 'Thirty'), ('40대', 'Fourty'), ('50대', 'Fifty'), ('60대', 'Sixty')], default='20대', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남자', 'Male'), ('여자', 'Female')], default='20대', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('서울', 'Seoul'), ('부산', 'Busan'), ('대구', 'Daegu'), ('인천', 'Incheon'), ('광주', 'Gwangju'), ('대전', 'Daejeon'), ('울산', 'Ulsan'), ('세종', 'Sejong'), ('경기', 'Gyeonggi'), ('강원', 'Gangwon'), ('충북', 'Chungbuk'), ('충남', 'Chungnam'), ('전북', 'Jeonbuk'), ('전남', 'Jeonnam'), ('경북', 'Gyeongbuk'), ('경남', 'Gyeongnam'), ('제주', 'Jeju')], default='20대', max_length=30),
        ),
    ]
