# Generated by Django 3.2.10 on 2022-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='random_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='random name'),
        ),
    ]
