version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: kkanbu_staging_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.staging/.postgres
    ports:
      - 5432:5432

  redis:
    image: redis:6
    container_name: redis
    ports:
      - 6379:6379
