# Generated by Django 3.2.10 on 2022-02-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentblame',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postblame',
            options={},
        ),
        migrations.AddConstraint(
            model_name='commentblame',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_user_per_comment'),
        ),
        migrations.AddConstraint(
            model_name='postblame',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_user_per_post'),
        ),
    ]
