# Generated by Django 3.2.11 on 2022-03-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_commentlike_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='commentblame',
            name='unique_user_per_comment',
        ),
        migrations.RemoveConstraint(
            model_name='postblame',
            name='unique_user_per_post',
        ),
        migrations.AddConstraint(
            model_name='commentblame',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_commentblame'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_commentlike'),
        ),
        migrations.AddConstraint(
            model_name='postblame',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_postblame'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_postlike'),
        ),
    ]
