# Generated by Django 3.2.11 on 2022-08-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20220320_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblame',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentblame',
            name='reason',
            field=models.CharField(choices=[('abuse', '욕설'), ('defame', '비방'), ('spam', '도배'), ('falsefact', '허위사실'), ('advertise', '광고'), ('incorrect', '게시판미부합'), ('etc', '기타사항')], default='etc', max_length=30),
        ),
        migrations.AddField(
            model_name='postblame',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postblame',
            name='reason',
            field=models.CharField(choices=[('abuse', '욕설'), ('defame', '비방'), ('spam', '도배'), ('falsefact', '허위사실'), ('advertise', '광고'), ('incorrect', '게시판미부합'), ('etc', '기타사항')], default='etc', max_length=30),
        ),
    ]
