# Generated by Django 3.2.11 on 2022-02-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('postlike', 'Postlike'), ('commentlike', 'Commentlike'), ('postblame', 'Postblame'), ('commentblame', 'Commentblame')], max_length=20),
        ),
    ]
