# Generated by Django 3.2.11 on 2022-03-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
    ]
