# Generated by Django 3.2.10 on 2022-02-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
