# Generated by Django 3.2.11 on 2022-03-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
