# Generated by Django 3.2.11 on 2022-05-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='sogaetingoption',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='app',
            field=models.CharField(choices=[('Topic', '토픽'), ('PitAPat', '두근두근')], default='Topic', max_length=30),
        ),
        migrations.AddField(
            model_name='sogaetingoption',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sogaetingoption',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, '남자'), (2, '여자')], default=1),
        ),
        migrations.AlterField(
            model_name='sogaetingoption',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sogaetingoption', serialize=False, to='board.post'),
        ),
        migrations.AlterField(
            model_name='sogaetingoption',
            name='region',
            field=models.CharField(choices=[('SO', '서울'), ('BS', '부산'), ('DG', '대구'), ('IC', '인천'), ('GJ', '광주'), ('DJ', '대전'), ('US', '울산'), ('SJ', '세종'), ('GG', '경기'), ('GW', '강원'), ('CB', '충북'), ('CN', '충남'), ('JB', '전북'), ('JN', '전남'), ('GB', '경북'), ('GN', '경남'), ('JJ', '제주')], default='SO', max_length=30),
        ),
    ]
