# Generated by Django 3.2.11 on 2022-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sogaetingoption',
            name='region',
            field=models.CharField(choices=[('Seoul', '서울'), ('Busan', '부산'), ('Daegu', '대구'), ('Incheon', '인천'), ('Gwangju', '광주'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기'), ('Gangwon', '강원'), ('Chungbuk', '충북'), ('Chungnam', '충남'), ('jeonbuk', '전북'), ('Jeonnam', '전남'), ('Gyeongbuk', '경북'), ('Gyeongnam', '경남'), ('Jeju', '제주')], default='Seoul', max_length=30),
        ),
    ]
