# Generated by Django 3.2.11 on 2022-08-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterField(
            model_name='sogaetingoption',
            name='region',
            field=models.CharField(choices=[('서울', 'Seoul'), ('부산', 'Busan'), ('대구', 'Daegu'), ('인천', 'Incheon'), ('광주', 'Gwangju'), ('대전', 'Daejeon'), ('울산', 'Ulsan'), ('세종', 'Sejong'), ('경기', 'Gyeonggi'), ('강원', 'Gangwon'), ('충북', 'Chungbuk'), ('충남', 'Chungnam'), ('전북', 'Jeonbuk'), ('전남', 'Jeonnam'), ('경북', 'Gyeongbuk'), ('경남', 'Gyeongnam'), ('제주', 'Jeju')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(('comment__length__gte', 4)), name='comment_length_gte_4'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('title__length__gte', 4)), name='title_length_gte_4'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('content__length__gte', 4)), name='content_length_gte_4'),
        ),
        migrations.AddConstraint(
            model_name='sogaetingoption',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 20)), name='age_gte_20'),
        ),
    ]
